### ISSUE TITLE
Thumbnails not showing up

### ISSUE THREAD

**Issue by csyversen** [nulib/donut#101]
Here's a good example: http://donut.repo.rdc-staging.library.northwestern.edu/concern/images/cee2e75c-1d2e-4551-a46b-661878aa9b5d?locale=en#?c=0&m=0&s=0&cv=0&xywh=-783%2C-58%2C2588%2C1137

The images show up in the universal viewer, but there aren't any representative images showing up on the #show page. 

I'm seeing this error in the logs: 
```
I, [2018-01-23T18:23:09.387540 #26275]  INFO -- : [239a4161-c3be-4b85-a51b-0e01a357da65] Started POST "/" for 127.0.0.1 at 2018-01-23 18:23:09 +0000
D, [2018-01-23T18:23:09.427695 #26275] DEBUG -- : [239a4161-c3be-4b85-a51b-0e01a357da65]   Load LDP (21.5ms) http://fcrepo.repo.vpc.rdc-staging.library.northwestern.edu/rest/bb/52/0f/f8/bb520ff8-9d94-47db-9107-cd0b275b9ad0 Service: 47398585891020
D, [2018-01-23T18:23:09.493206 #26275] DEBUG -- : [239a4161-c3be-4b85-a51b-0e01a357da65]   Hyrax::Operation Load (1.8ms)  SELECT  "curation_concerns_operations".* FROM "curation_concerns_operations" WHERE "curation_concerns_operations"."id" = $1 LIMIT $2  [["id", 167], ["LIMIT", 1]]
F, [2018-01-23T18:23:09.495636 #26275] FATAL -- : [239a4161-c3be-4b85-a51b-0e01a357da65]
F, [2018-01-23T18:23:09.496104 #26275] FATAL -- : [239a4161-c3be-4b85-a51b-0e01a357da65] ActiveRecord::RecordNotFound (Couldn't find Hyrax::Operation with 'id'=167):
F, [2018-01-23T18:23:09.496198 #26275] FATAL -- : [239a4161-c3be-4b85-a51b-0e01a357da65]
F, [2018-01-23T18:23:09.496325 #26275] FATAL -- : [239a4161-c3be-4b85-a51b-0e01a357da65] activerecord (5.1.4) lib/active_record/relation/finder_methods.rb:343:in `raise_record_not_found_exception!'
```

which is weird, because i can pull up that record in the rails console. Maybe it's a race condition or something? 

Anyway i'm looking into this now

**Comment by csyversen** [comment]
(related to #83)

**Comment by kdid** [comment]
CharacterizationJob when called from the ImportUrlJob is looking for files in `/tmp...` on the worker box running the job. Which may or not be the same worker box where the file is. 

We just did some troubleshooting on the File Upload issue through the UI and even though derivatives are being created, they are being stored on the worker box and the webapp doesn't have access to them to display. We opened issue https://waffle.io/nulib/repodev_planning_and_docs/cards/5a6a1421395a2d0031699422 about these Hyrax assumptions regarding local file systems. (Those issues will come into play here as well)

As far as the images showing in the UV - those are coming from Fedora so would be available even if derivatives aren't created. 

Here's the error in the logs for reference:
```
E, [2018-01-25T16:50:22.895723 #26268] ERROR -- : [1eae35d0-4749-426f-990e-b57bff44db89] [ActiveJob] [CharacterizeJob] [fe0e166c-9049-45d6-a0d4-26fdd9298ff7] Error performing CharacterizeJob (Job ID: fe0e166c-9049-45d6-a0d4-26fdd9298ff7) from BetterActiveElasticJob(default) in 8905.32ms: RuntimeError (Unable to execute command "/usr/local/fits-1.0.5/fits.sh -i "/tmp/d20180125-26268-sdub1r/nul.jpg""
Picked up JAVA_TOOL_OPTIONS: -Xmx128m
Jan 25, 2018 4:50:21 PM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsConfigurationException: /tmp/d20180125-26268-sdub1r/nul.jpg does not exist or is not readable
	at edu.harvard.hul.ois.fits.Fits.examine(Fits.java:522)
	at edu.harvard.hul.ois.fits.Fits.doSingleFile(Fits.java:405)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:291)
```

@davidschober

**Comment by adamjarling** [comment]
Abandoned, and will create issues from #303.
