### ISSUE TITLE
derivatives not being generated donut.stack.rdc-staging

### ISSUE THREAD

**Issue by davidschober** [nulib/donut#307]
## Description

After the rebuild of donut, derivatives are not shown (either the pyramid in the UV or thumbnails)

## To recreate
- go to http://donut.stack.rdc-staging.library.northwestern.edu
- upload a tif
- see that derivatives are not generated http://donut.stack.rdc-staging.library.northwestern.edu/concern/images/a20ff876-2e24-4204-a622-a06c0a5ca08f?locale=en#?c=0&m=0&s=0&cv=0

**Comment by kdid** [comment]
resolved.
