### ISSUE TITLE
Meet to discuss s3 bucket pipeline

### ISSUE THREAD

**Issue by carrickr** [nulib/donut#35]
## Description

- do we need to have automated process for this> 
- What does the process look like (avalon inspired)
- Do we have a UI or a magical manifest sensing 
- Review <https://github.com/nulib/next-generation-repository/wiki/Batch-Ingestion-Workflow>

## Done looks like

- [x] workflow meeting takes place
- [x] document the s3 pipeline and workflow
-  [ ] ~Create a bucket!~ 
- [ ] ~Create Cyberduck script for any user to upload to bucket (for staging we can have one generic user)~

**Comment by davidschober** [comment]
### Workflow

- Batch ingestion will mimic Avalon:
   + a Spreadsheet will be generated as a manifest sidecar 
   + S3 will fire off a job when spreadsheet is present
   + stuff will get ingested


- How do we want to handle collection
    + If you leave collection ID blank it blows up Decide ho to deal with this
    + A thing can be in 0 or many collections, so collection should be optional, but for the purposes of spreadsheet something can be in one collection, people could use a default "recent batches" 

- Can we have a field for Admin sets
    + You can't create a work without an admin set, it seems to be adding to default

**Comment by davidschober** [comment]
Work to be completed in #54
