### ISSUE TITLE
Create Job That Deletes Masterfiles in the pending bucket after ingest success

### ISSUE THREAD

**Issue by carrickr** [nulib/donut#36]
Once CreateWorkJob has successfully ingested a resource, CreateWorkJob should enqueue a cleanup job for that masterfile.  This could be done via hooks or by calling out to super for CreateWorkJob and then adding in desired code.

This job should delete the file from the pending bucket (#35)

## Done looks like
- [ ] job is written that cleans up after a successful ingest.

**Comment by davidschober** [comment]
@carrickr can you detail this out more? I'm a bit confused by the done criteria.

**Comment by kdid** [comment]
closing. No longer relevant to current process.
