### ISSUE TITLE
Editing a work, Location dropdown doesn't seem to work

### ISSUE THREAD

**Issue by adamjarling** [nulib/donut#373]
### Description
In my local version of Donut, I can't get any values to populate when searching for "Location" when editing a work.  So I can't add a Location to a work to test if it's pulling through to the React app.

#### To recreate
Edit a work
Try typing in a value for "Location" field.

![edit-work-location-field-error](https://user-images.githubusercontent.com/3020266/47302704-c9868c80-d5e7-11e8-823a-2bfa32efa8af.png)

**Comment by kdid** [comment]
Hey @adamjarling - Do you have the geonames credentials configured in your `config/settings.local.yml` file?

https://github.com/nulib/donut#dependencies

(I'll Slack it to you if you don't have the username)
