### ISSUE TITLE
Add these metadata fields to the Indexer so they pull through to the React app

### ISSUE THREAD

**Issue by adamjarling** [nulib/donut#374]
### Description
@jenyoung pointed out in https://github.com/nulib/next-generation-repository/issues/749 that certain fields are not pulling through to the front end React app.   These need to get added to the indexer.

### Done Looks Like
The React app displays the metadata items listed in the above ticket.  

### To Do
- [ ] Add the following fields to the Indexer:

- Notes
- Related material
- Scope and contents
- Series
- Subject temporal
- Table of contents

@kdid

**Comment by kdid** [comment]
Closing, moved to next-generation-repository repo: https://github.com/nulib/next-generation-repository/issues/759
