### ISSUE TITLE
Compare current validation with BFF spreadsheet and Image model required fields

### ISSUE THREAD

**Issue by carrickr** [nulib/donut#38]
Primarily for Berkeley at this point, given JSON validate it and determine if a resource can be created or not.  If it cannot write error to log.

For MVP required validations are:

- File is present in the S3 bucket
- It has a title
- It has a collection to put it in

### Done Looks Like
- [ ] Update validator to conform to Northwestern model.

**Comment by davidschober** [comment]
@carrickr do we need validation outside of what Hyrax does? Or am I misunderstanding the scope of the issue.

**Comment by carrickr** [comment]
We want to validate it before throwing off a job to the queue (and Hyrax has no concept of how to work with S3 right now so we need to handle the file checks and stuff)

**Comment by bmquinn** [comment]
https://github.com/nulib/donut/wiki/Batch-uploads-via-CSV
