### ISSUE TITLE
Ensure that Berkeley Spreadsheets are supported by current images model

### ISSUE THREAD

**Issue by carrickr** [nulib/donut#40]
[Spreadsheet example](https://docs.google.com/spreadsheets/d/1CpTzBySASaTGhH0GGabZiJU3S6xrlF5PMYmwzRhyL2Y/edit?usp=drive_web)

[Predicate and PCDM](https://docs.google.com/spreadsheets/d/1F35hLSD11a1mf9UTXvgAc7xKXkAixOaBwVvzYQulnkc/edit#gid=396400352)

Ensure that all the columns that need to be ingested (note not all columns need to be ingested, such as BE and BF) map to something in the Images resource for DONUT.

Spawn tickets to expand resource as needed.  The tickets can be done in a later phase.

**Comment by carrickr** [comment]
We'll focus on required fields, I'll generate a fixture spreadsheet, attach it to this issue and close it out.

**Comment by davidschober** [comment]
Carrick will timebox.

**Comment by davidschober** [comment]
@carrickr is this holding over or should we close and kick off new issues?

**Comment by carrickr** [comment]
I'm not seeing anything in Berkeley that is a deal breaker, it's just going through and adding fields to our Image Type generator in Hyrax, I'll put in a donut ticket for this.
