### ISSUE TITLE
Verify Various Failure States Log Errors

### ISSUE THREAD

**Issue by carrickr** [nulib/donut#43]
## Description

When derivatives are created successfully, make it fail and follow the failure through the logs to verify we're logging.  Beside #38 where an error is written if the metadata is invalid, ensure all the other edge cases write out errors, namely:

- Fedora timeouts
- Derivative Failures
- File not found on S3
- Error opening/reading CSV

**Comment by davidschober** [comment]
@carrickr is this abandoned? I think it is...

**Comment by carrickr** [comment]
@bmquinn @mbklein @kdid 

Abandon?  

@davidschober while I broke these down long ago, I'm no longer really their owner

**Comment by bmquinn** [comment]
We've covered this in the batch-refactor branch. Closing.
