### ISSUE TITLE
Workflow Task Force crosswalk info

### ISSUE THREAD

**Issue by ccaizzi** [nulib/donut#449]
@davidschober  and @jenyoung please sit down and go over the "rosetta stone" in case it impacts this cycle and the MVP batch ingest.
## Done looks like
- [ ] meeting is held between @jenyoung and @davidschober 
- [ ] Docs are written if necessary, shared understanding gained
- [ ] high-fives all around.

**Comment by davidschober** [comment]
closing as stale.
