### ISSUE TITLE
Refactor route for omniauth callbacks

### ISSUE THREAD

**Issue by csyversen** [nulib/donut#48]
We're getting a deprecation warning: ```DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 5.2. (called from block (2 levels) in <top (required)> at /home/travis/build/nulib/donut/config/routes.rb:15)```

here: https://github.com/nulib/donut/blob/deploy/staging/config/routes.rb#L15

We should refactor this sooner rather than later, but Carrick and I weren't sure what the new syntax was and didn't want to spend all day on it. I'm putting in this issue as a reminder that we'll need to change this before rails 5.2 is released (which is kind of soon)

**Comment by davidschober** [comment]
@csyversen and @carrickr what's the time horizon for Rails 5.2?

**Comment by carrickr** [comment]
Hyrax 3
