### ISSUE TITLE
Trigger ingest from S3 add/update

### ISSUE THREAD

**Issue by mbklein** [nulib/donut#54]
When an ingest manifest spreadsheet is added to the correct S3 bucket, trigger ingest via the queue.

- [x] Jobify the existing command line app
- [ ] Rewrite the command line app to run through the job class
- [ ] Set up the S3 notification and queueing
- [ ] Carrick will test out batch import

**Comment by carrickr** [comment]
Run BatchImport to check perform_later functionality under aws-sdk v3

**Comment by davidschober** [comment]
@carrickr this got done today correct?

**Comment by carrickr** [comment]
This has not been done on donut, this is done on Avalon

**Comment by davidschober** [comment]
I pulled this out of the current  sprint.

**Comment by adamjarling** [comment]
@carrickr We think this is done.  Verify with @bmquinn ?

**Comment by adamjarling** [comment]
This is done in Avalon.  Donut?  Seems so.
