### ISSUE TITLE
Check DONUT for redis-store security flaw

### ISSUE THREAD

**Issue by carrickr** [nulib/donut#76]
```The redis-store dependency defined in Gemfile.lock has a known high severity security vulnerability in version range < 1.4.0 and should be updated.```

This kicked in with Avalon, it may impact DONUT and DONUT might be a Gemfile update.  

https://github.com/avalonmediasystem/avalon/pull/2702 shows the fix in Avalon

**Comment by csyversen** [comment]
we're good, donut is at 1.4.1 and we're not getting the warning anymore
