### ISSUE TITLE
figure out why derivatives aren't working on AWS (for batch upload)

### ISSUE THREAD

**Issue by csyversen** [nulib/donut#83]
batch uploads are creating derivative images locally, but aren't when we run it on staging. Look into why! We know this was working before, the Import URLs were being double encoded in a way that was easy to fix. We had it working using Minio in local dev environments. 

- [x] Checked workers, they're running
- [x] Checked app for errors
- [ ] We have to investigate where the double encoding is hyrax and fix it upstream. 
- [ ] Test with Bespoke Fedora (maybe it was simultaneous writes
- [ ] Create more verbose log to dig into

**Comment by davidschober** [comment]
This is not just batch. Derivatives don't seem to be being updated for items uploaded through the UI.

**Comment by davidschober** [comment]
CC: Does Hydra Derivatives save things asynchronously?

**Comment by davidschober** [comment]
MBK: Even though Michael is 48 years old he will attempt to remember.... I have an idea, but I'm in the parking garage. I will remember.

**Comment by csyversen** [comment]
on a happier note, upping the log level helps. The workers are now logging that they aren't able to find the file (which is the same issue we were having locally when things were getting encoded too many times locally too) 

```
Errno::ENOENT (No such file or directory @ rb_sysopen - /var/donut-temp/hyrax/uploaded_file/file/34/AAEAAQAAAAAAAALwAAAAJDliZTVkOTcyLWQ0NzUtNDNlZC1hZmEwLTY1NTQ0ZDBjNTE5ZA.jpg)
```

**Comment by csyversen** [comment]
spawned #87 and #89 so far

**Comment by csyversen** [comment]
spawned #94 

#87 and #89 are closed

**Comment by csyversen** [comment]
this issue is a symptom of a larger one: https://github.com/nulib/next-generation-repository/issues/303

**Comment by csyversen** [comment]
talked to @bmquinn and @kdid , we decided to use nulib/next-generation-repository#303 as the base of work instead of keeping two related tickets up to date
