### ISSUE TITLE
Figure out a way to avoid env checking for S3 urls

### ISSUE THREAD

**Issue by bmquinn** [nulib/donut#96]
## Description

URL encoding is handled differently between Minio and S3. This is being handled by checking the Rails environment now, but that is not ideal.

## Done looks like:

- Conditional logic removed from Importer::Factory::ObjectFactory for Rails environment.

**Comment by davidschober** [comment]
@bmquinn is this required for .4

**Comment by csyversen** [comment]
@davidschober i was working on this with brendan, no it's not required for .4. It's technical debt that needs to get fixed at some point though

**Comment by bmquinn** [comment]
+1

**Comment by kdid** [comment]
closing. No longer relevant.
